#### NumPy는 “Numerical Python“의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
* Numerical Python을 의미하는 NumPy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
* 많은 머신러닝 알고리즘이 넘파이 기반으로 작성돼 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
* 넘파이의 기본 데이터 타입은 ndarray. ndarray를 이용해 넘파이에서 다차원 배열을 쉽게 생성하고 다양한 연산 수행

NumPy 특징

- 강력한 N 차원(다차원) 배열 객체
- 정교한 브로드케스팅(Broadcast) 기능
- C/C ++ 및 포트란 코드 통합 도구
- 유용한 선형 대수학, 푸리에 변환 및 난수(랜덤한 수) 기능
- 푸리에 변환(Fourier transform, FT)은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

Numpy Documentation  

https://numpy.org/doc/1.21/index.html

Numpy는 대용량 데이터 배열을 효율적으로 다룰 수 있도록 설계되었다.
- Numpy는 내부적으로 데이터를 다른 내장 파이썬 객체와 구분된 연속된 메모리 블록에 저장
- Numpy의 각종 알고리즘은 모두 C로 작성되어 타입 검사나 다른 오버헤드 없이 메모리를 직접 조작
- Numpy 배열은 또한 내장 파이썬의 연속된 자료형들보다 훨씬 더 적은 메모리를 사용
- Numpy 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산을 수행

In [3]:
import numpy as np
my_arr=np.arange(1000000) #0~999999까지 
my_list=list(range(1000000))

%time for _ in range(10): my_array2=my_arr*2


Wall time: 24.4 ms


In [4]:
%time for _ in range(10): my_list2=[x*2for x in my_list] #위의 식과 같은건데 소요시간 차이가 큼
                                                        # 배열이 더 효과적임.

Wall time: 759 ms


In [8]:
#배열 연산
np.random.seed(0) #랜덤값 고정
data= np.random.randn(2,3)
print(data,'\n')
print(data*10,'\n') #각 값에 전부 10이 곱해짐

print(data+data) #각 값끼리 더해짐

[[ 1.76405235  0.40015721  0.97873798]
 [ 2.2408932   1.86755799 -0.97727788]] 

[[17.64052346  4.00157208  9.78737984]
 [22.40893199 18.6755799  -9.7727788 ]] 

[[ 3.52810469  0.80031442  1.95747597]
 [ 4.4817864   3.73511598 -1.95455576]]


In [12]:
#데이터의 크기 확인

print(data.shape) #크기(몇행 몇열인지)
print(data.dtype) #자료형
print(data.ndim) #차원

(2, 3)
float64
2


In [14]:
#배열생성(array)

data1=[6,7,5,8,0,1] #이렇게 리스트가 있을 때 
arr1=np.array(data1)
print(arr1,type(arr1)) #1차원 배열

[6 7 5 8 0 1] <class 'numpy.ndarray'>


In [19]:
#2차원 배열 만들어보기 
data2=[[1,2,3,4],[5,6,7,8]]
arr2=np.array(data2)
print(arr2,type(arr2),'\n')  #전체의 타입
print(arr2.shape,'\n')
print(arr2.ndim,'\n')
print(arr2.dtype) #입력값의 타입 = 정수

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 

(2, 4) 

2 

int32


In [21]:
#3차원 배열 만들어보기

data3=[[[1,2,3,4,5],[6,7,8,9,10]],
       [[1,2,3,4,5],[6,7,8,9,10]],
       [[1,2,3,4,5],[6,7,8,9,10]]]
arr3=np.array(data3)
print(arr3,type(arr3),'\n')
print(arr3.shape,'\n')
print(arr3.ndim,'\n')
print(arr3.dtype)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]] <class 'numpy.ndarray'> 

(3, 2, 5) 

3 

int32


배열 생성 및 초기화
- Numpy는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

In [24]:
print(np.zeros(10)) #원소를 10개로 하는 배열을 만들어준다
print(np.zeros((3,5))) #2차원도 가능. 이때 가로도 추가됨
print(np.zeros((2,3,2))) #3행 2열짜리 2개. 바깥 대괄호가 3차원임을 표시함 

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [26]:
print(np.ones(10),'\n') #위와 같으나 0대신 1이 들어간다
print(np.ones((3,5)),'\n') 
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] 

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [ ]:
#[과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.

In [2]:
import numpy as np
a=np.arange(10).reshape(2,5)
print(a)

print(np.zeros_like(a),'\n')
print(np.ones_like(a),'\n')
print(np.full_like(a,2)) #full은 임의의 어떤 수를 넣어줘야함

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 0 0 0 0]
 [0 0 0 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]] 

[[2 2 2 2 2]
 [2 2 2 2 2]]


In [56]:
#arange 함수: 파이썬의 range함수의 배열버전
ar=np.arange(15)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
#reshape 함수 (shape 을 다시 만든다)
ar.reshape(3,5) #원래 어레인지가 15개라 그 갯수를 맞춰줘야 한다. 
#ar.reshape(1,15)=2차원

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [63]:
#Q.array1에 reshape 함수를 이용 (5,2) 배열을 생성하고 형태를 같이 출력하세요.

array1=np.arange(10)
array1.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [64]:
#Q.ar에 reshape()함수 이용. 1차원,2차원,3차원 배열 생성

In [75]:
ar=np.arange(10)
ar

ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [70]:
ar.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
ar.reshape(2,5,1)

array([[[0],
        [1],
        [2],
        [3],
        [4]],

       [[5],
        [6],
        [7],
        [8],
        [9]]])

In [ ]:
ar = np.arange(12)
print(ar.reshape(12), '\n')
print(ar.reshape(3,4), '\n')
print(ar.reshape(2,3,2))

In [108]:
#차원변경
ar1=np.arange(30) #0부터 29까지의 수로 이루어진 1차원
print('1->2,3차원')

ar12=ar1.reshape(2,-1)
#ar1을 2행 n열의 2차원 배열로 변환
#두 번째 인수를 -1로 지정,
#ar1의 원소 개수인 30개를 2행으로 나누면 15가 되므로, ar12는 2행 15열의 2차원 배열이 됨

ar13=ar1.reshape(-1,2,5)
#ar1을 3차원 배열로 변환
#첫 번째 인수를 -1로 지정.  ar1의 원소 개수인 30개를 2x5로 나누면 3이 되므로, 
#ar13는 3개의 2행 5열의 2차원 배열이 3개 필요하므로 3차원으로 결정

print(ar13)

1->2,3차원
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [80]:
print('2차원->1,3차원')

print(ar12,'\n')
ar21=ar12.reshape(-1,) #1차원일 땐 이렇게만 해줘도 됨.
ar23=ar12.reshape(-1,2,5) #-1(자동설정값만큼의)2행 5열로 알아서 처리해줌
print(ar21,'\n')
print(ar23)

2차원->1,3차원
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
#차원의 개수는 배열(array)을 구성하는 블록(block)의 개수로 결정됩니다
# (3, 2, 5) 형태의 배열은 3개의 2차원 배열을 요소로 가지는 3차원 배열이며, 
#(3, 10) 형태의 배열은 3개의 1차원 배열을 요소로 가지는 2차원 배열입니다. 
#이때, 배열의 shape에 따라 블록의 수가 결정되며, dtype은 각 요소(block)의 데이터 타입을 결정합니다.

In [81]:
print('3차원->1,2차원')

ar31=ar13.reshape(-1,)
ar32=ar13.reshape(3,-1) #행을 3으로 하고 알아서 해
print(ar31,'\n')
print(ar32)

3차원->1,2차원
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [84]:
ar3=np.arange(30).reshape(3,2,5)
print(ar3,type(ar3))
#리스트로 바꿀 때
l3=ar3.tolist()
print(l3,type(l3))
#리스트를 다시 바꿀 땐 array 쓰면 됨

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] <class 'numpy.ndarray'>
[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]], [[10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29]]] <class 'list'>


행렬의 종류

https://math-development-geometry.tistory.com/52

- 정방행렬은 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 삼각행렬은 주대각선 원소를 기준으로 위 또는 아래에 있는 성분이 모두 0인 정방행렬
  - 상삼각행(upper): 아래성분이 모두 0
  - 하삼각행렬(lower): 위의 성분이 모두 0
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬(주 대각선이 다 1.나머지 0)
  - 항등행렬에 다른 행렬을 곱사면 결과는 곱한 행렬이 그대로 나온다=단위행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을때 항등행렬이 나오는 행렬

In [86]:
# 정방행렬
+
a=np.full((2,2),7) #행과 열의 수가 같아야 한다. full=특정 함수로 채워야 함 ex)7
a

array([[7, 7],
       [7, 7]])

In [88]:
#항등행렬, 단위 행렬

ar=np.eye(3) #3은 대각선의 갯수.
ar


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [89]:
#대각행렬

diag_mat=np.diag([1,2,3,4,5])
diag_mat

#diag: 대각행렬을 생성하는 함수

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [90]:
#삼각행렬
#upper = 아랫쪽이 다 0
upper_tri_mat=np.triu([[1,2,3],[4,5,6],[7,8,9]]) #대괄호 2번 들어감
print(upper_tri_mat)

#triu= 상삼각 행렬을 생성하는 코드 

[[1 2 3]
 [0 5 6]
 [0 0 9]]


##### [과제] 하 삼각행렬을 생성하세요

In [106]:
lower_tri_mat=np.tril([[1,2,3],[4,5,6],[7,8,9]]) 
print(lower_tri_mat)

#tril= 하삼각 행렬을 생성하는 코드

[[1 0 0]
 [4 5 0]
 [7 8 9]]


In [113]:
#전치행렬: 원래의 행과 열을 바꿈.

mat=np.array([[1,2],[3,4],[5,6]])
print(mat,'\n') #= 3행 2열

transpose_mat=mat.T
print(transpose_mat) #2행 3열

[[1 2]
 [3 4]
 [5 6]] 

[[1 3 5]
 [2 4 6]]


#### 직교 행렬 
- 행과 열이 서로 직교하는 정방행렬
- 모든 열 백터와 행 백터가 서로 직교하고, 크기가 1인 단위백터로 이루어짐
- np.linalg.qr()함수를 사용하여 QR분해 수행하여 직교 행렬을 추출
- q를 추출하여 직교행렬을 만든다.
- np.dot(행렬곱: orth_mat,orth_mat.T)를 계산하여 직교성을 검증
- np.allcolse() 함수로 두 행렬이 동일한지 검사. True를 반환하면 두 행렬은 동일

In [118]:
#직교 행렬 : 행과 열이 서로 직교하는 정방행렬
#모든 열 백터와 행 백터가 서로 직교하고, 크기가 1인 단위백터
#A의 전치행렬과 A행렬을 곱하였을 때 항등행렬이 나오는 행렬

mat=np.random.randn(3,3)

print(mat,'\n')

#서로 직교되는걸 분해(qr)

q,r=np.linalg.qr(mat)

#직교행렬 추출
orth_mat=q
print(orth_mat)

#직교성 검증
print(np.allclose(np.dot(orth_mat,orth_mat.T),np.eye(3)))

#np.dot(행렬곱)=(orth_mat :직교행렬) x (orth_mat.T: 전치행렬)
#npdot = np.eye(3) 이면 항등행렬

#print(q)
#print(r)


[[-1.70627019  1.9507754  -0.50965218]
 [-0.4380743  -1.25279536  0.77749036]
 [-1.61389785 -0.21274028 -0.89546656]] 

[[-0.71418111  0.58409529 -0.38571756]
 [-0.18336158 -0.68793021 -0.70223255]
 [-0.67551749 -0.43079544  0.59840739]]
True


In [119]:
#인덱싱, 슬라이싱
ar2=np.arange(1,10).reshape(3,3)
ar2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [126]:
print(ar2[2])
print(ar2[0][2])
print(ar2[0,2])

[7 8 9]
3
3


In [127]:
ar=np.arange(20).reshape(5,4)
ar

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [128]:
ar[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [130]:
#Q.ar에서 슬라이싱을 사용해서 아래와 같이 출력하세요. 
ar=np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
print(ar[:2,:2])
print(ar[1:])
print(ar[:])

print(ar[:2,0])



[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4]


In [154]:
ar[:2,:2]
ar[1:]
ar[:]
ar[0:2,1:]
ar[0:2,:1]

print(ar[:2,:2],'\n')
print(ar[1:],'\n')
print(ar[1:,:])
print(ar[:])
print(ar[:2,1:],'\n')
print(ar[:2,0])

[[1 2]
 [4 5]] 

[[4 5 6]
 [7 8 9]] 

[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]] 

[1 4]


In [145]:
#[과제]ar에서 인덱스를 이용해서 값을 선택하고 리스트로 아래와 같이 출력하세요.

In [4]:
ar=np.arange(1,10).reshape(3,3)
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
[3,6]
[[1,2],[4,5]]
[[1,2,3],[4,5,6]]

In [6]:
#박주경
ar = np.arange(1,10).reshape(3,3)

print(list(ar[:2, 2]))
print(ar[:2, :2].tolist())
print(ar[:2].tolist())

[3, 6]
[[1, 2], [4, 5]]
[[1, 2, 3], [4, 5, 6]]


In [146]:
#Boolean indexing
ar=np.arange(1,10)
ar

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
ar[ar>5]

array([6, 7, 8, 9])

In [148]:
#Q. 1~14 까지 ndarray를 만들어 array_e로 저장하고 (array_e/2)>5 를 만족하는 값을 불린 인덱스로 출력

In [151]:
ar=np.arange(1,15)
ar

ar[ar/2 > 5]

array([11, 12, 13, 14])

In [181]:
#arr에서 0.5보다 큰 수를 출력하세요
np.random.seed(0)
arr=np.random.rand(30)
arr

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ,
       0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606,
       0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443,
       0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194])

In [182]:
arr[arr>0.5]

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.64589411,
       0.891773  , 0.96366276, 0.79172504, 0.52889492, 0.56804456,
       0.92559664, 0.83261985, 0.77815675, 0.87001215, 0.97861834,
       0.79915856, 0.78052918, 0.63992102, 0.94466892, 0.52184832])

In [192]:
#data에서 3의 배수인 수만 출력하세요
np.random.seed(0)
data=np.arange(30)


In [193]:
data[data%3==0]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

##### [과제][1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열형태로 출력하세요

np.where(condition)은 
- condition 배열의 요소가 True인 인덱스를 반환하는 함수입니다. 
- condition 배열은 bool 타입이어야 하며, 반환값은 tuple 타입으로 (array of row indices, array of column indices)의 형태로 반환

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
array=np.where(arr>5)
array #인덱스넘버가 나온다. 1행 2열. 2행 0열, 
#5보다 큰 인덱스값이 나온다.=튜플반환. 1행의 2열, 2행의 0,1,2열 

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [ ]:
array=np[0]

In [10]:
a=np.array([1,2,0,0,4,0])
nz=np.nonzero(a) #0이 아닌 인덱스를 뽑아낸다. 0번 인덱스(1) 1번 인덱스(2) 4번 인덱스(4)
nz
#0이 아닌 '값'이 아닌 0이 아닌 '인덱스'를 뽑아내라는 문제
#0이 아닌 값이었으면 1,2,4

(array([0, 1, 4], dtype=int64),)

np.nonzero(a) 함수는 배열 a의 0이 아닌 요소의 인덱스를 반환합니다. 반환값은 인덱스를 담은 튜플 형태로 반환되는데, 이때 0이 아닌 요소의 인덱스는 각 차원별로 배열로 묶여서 반환됩니다.

따라서 a=np.array([1,2,0,0,4,0]) 배열에서 0이 아닌 요소의 인덱스는 0, 1, 4입니다. 이들은 1차원 배열 상에서 각각 0번, 1번, 4번 인덱스에 해당하므로 (array([0, 1, 4], dtype=int64),)와 같은 결과가 반환됩니다.

만약 반환값으로부터 인덱스 배열을 추출하고 싶다면, nz[0]과 같이 첫 번째 요소를 인덱싱하면 됩니다. 즉, nz[0]은 array([0, 1, 4], dtype=int64)를 반환합니다.

In [ ]:
np.where(a!=0,1,0)

In [8]:
#김나영
#과제: 0이 아닌 값 인덱스를 배열형태로 출력
a=np.array([1,2,0,0,4,0])

index=np.where(a!=0)     #조건을 만족하는 인덱스를 반환
print(index)
print(index[0])           #[0]에 인덱스 값, [1]에 타입값

(array([0, 1, 4], dtype=int64),)
[0 1 4]


In [195]:
bools=np.array([False,False,True,True])
bools

array([False, False,  True,  True])

In [197]:
#any 메서드: 하나 이상의 값이 True인지 검사
bools.any()

True

In [196]:
#all 메서드: 모든 원소가 True인지 검사
bools.all()

False

In [198]:
#Q.arr에서 0보다 크면 2, 아니면 -2로 변경하세요 
arr=np.random.randn(4,4)
arr

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351],
       [ 0.76103773,  0.12167502,  0.44386323,  0.33367433]])

In [199]:
np.where(arr >0,2,-2) #0보다 크면 2, 아니면 -2 

array([[ 2,  2,  2,  2],
       [ 2, -2,  2, -2],
       [-2,  2,  2,  2],
       [ 2,  2,  2,  2]])

In [ ]:
#Q. arr의 모든 양수를 2로 바꾸세요

In [210]:
arr=np.random.randn(4,4)
arr
np.where(arr>0,2,arr) #0보다 크면 2, 아니면 원래의 수

array([[-0.88778575, -1.98079647, -0.34791215,  2.        ],
       [ 2.        ,  2.        , -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  2.        ],
       [-0.50965218, -0.4380743 , -1.25279536,  2.        ]])

In [211]:
#np.sort: 복사본은 반환

np.random.seed(0)
arr=np.random.randint(1,100,size=10)
arr

array([45, 48, 65, 68, 68, 10, 84, 22, 37, 88])

In [212]:
print(np.sort(arr))
print(arr) #원본은 안바뀜

[10 22 37 45 48 65 68 68 84 88]
[45 48 65 68 68 10 84 22 37 88]


In [213]:
sorted=np.sort(arr) #sorted에 반환해야함
print(sorted)

[10 22 37 45 48 65 68 68 84 88]


In [217]:
#행렬이 2차원 이상일 경우 axis 축 값 설정을 통해 로우방향, 칼럼방향으로 정렬 수행

ar2=np.array([[8,12],
            [7,1]])
print(np.sort(ar2,axis=0)) #행 방향으로 sort가 됨. 

print(np.sort(ar2,axis=1))

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [222]:
#ndarray.sort() =>원본에 반영
np.random.seed(0)
arr=np.random.randint(10,size=10)
print(arr)
arr.sort()
arr

[5 0 3 3 7 9 3 5 2 4]


array([0, 2, 3, 3, 3, 4, 5, 5, 7, 9])

In [223]:
arr=np.random.randint(10,size=(10,10))
arr
#다차원 배열의 정렬은 sort 매서드에 넘긴 축에 따라 1차원 부분을 정렬

array([[7, 6, 8, 8, 1, 6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4, 3, 0, 3, 5, 0],
       [2, 3, 8, 1, 3, 3, 3, 7, 0, 1],
       [9, 9, 0, 4, 7, 3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6, 8, 4, 1, 4, 9],
       [8, 1, 1, 7, 9, 9, 3, 6, 7, 2],
       [0, 3, 5, 9, 4, 4, 6, 4, 4, 3],
       [4, 4, 8, 4, 3, 7, 5, 5, 0, 1],
       [5, 9, 3, 0, 5, 0, 1, 2, 4, 2],
       [0, 3, 2, 0, 7, 5, 9, 0, 2, 7]])

In [224]:
arr.sort(1) #열방향. default
arr

array([[1, 1, 6, 6, 7, 7, 7, 8, 8, 8],
       [0, 0, 3, 3, 4, 5, 5, 8, 9, 9],
       [0, 1, 1, 2, 3, 3, 3, 3, 7, 8],
       [0, 0, 2, 2, 3, 4, 7, 7, 9, 9],
       [0, 1, 4, 4, 4, 5, 5, 6, 8, 9],
       [1, 1, 2, 3, 6, 7, 7, 8, 9, 9],
       [0, 3, 3, 4, 4, 4, 4, 5, 6, 9],
       [0, 1, 3, 4, 4, 4, 5, 5, 7, 8],
       [0, 0, 1, 2, 2, 3, 4, 5, 5, 9],
       [0, 0, 0, 2, 2, 3, 5, 7, 7, 9]])

In [225]:
arr.sort(0) #행방향
arr

array([[0, 0, 0, 2, 2, 3, 3, 3, 5, 8],
       [0, 0, 1, 2, 2, 3, 4, 5, 6, 8],
       [0, 0, 1, 2, 3, 3, 4, 5, 7, 8],
       [0, 0, 2, 2, 3, 4, 5, 5, 7, 9],
       [0, 1, 2, 3, 4, 4, 5, 6, 7, 9],
       [0, 1, 3, 3, 4, 4, 5, 7, 8, 9],
       [0, 1, 3, 4, 4, 5, 5, 7, 8, 9],
       [0, 1, 3, 4, 4, 5, 7, 8, 9, 9],
       [1, 1, 4, 4, 6, 7, 7, 8, 9, 9],
       [1, 3, 6, 6, 7, 7, 7, 8, 9, 9]])

In [226]:
#정렬된 행렬의 인덱스 반환: 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array=np.array([3,1,9,5])
sort_indices=np.argsort(org_array)
print(org_array)
sort_indices #sort한 기준으로 인덱스 반환

[3 1 9 5]


array([1, 0, 3, 2], dtype=int64)

In [227]:
#배열 데이터의 입출력
#np.save, np.load 는 바이너리 형식. npy 파일로 저장

arr=np.arange(10)
np.save('some_array',arr)

np.load('some_array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
#np.savez: 여러개의 배열을 압축된 형식으로 저장

np.savez('array_archive.npz',a=arr,b=arr)
arch=np.load('array_archive.npz')
arch['a']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [241]:
#Q.인덱싱을 사용하여 [1010101010]을 출력하세요
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr[:] = arr%2
arr

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [245]:
#강사님
a=np.ones(10,dtype=int)
a[[1,3,5,7,9]]=0
print(a)

[1 0 1 0 1 0 1 0 1 0]


In [ ]:
[과제] 1 ~ 100을 아래와 같이 출력하세요

In [ ]:

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>

In [13]:
#임수현
arr = np.arange(1,101).reshape(10,10)
arr[1::2] = arr[1::2, ::-1]
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 20,  19,  18,  17,  16,  15,  14,  13,  12,  11],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 40,  39,  38,  37,  36,  35,  34,  33,  32,  31],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 60,  59,  58,  57,  56,  55,  54,  53,  52,  51],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 80,  79,  78,  77,  76,  75,  74,  73,  72,  71],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [100,  99,  98,  97,  96,  95,  94,  93,  92,  91]])

In [12]:
#김나영
#과제: 홀수번째 줄만 거꾸로 뒤집기
arr = np.arange(1,101).reshape(10,10)

for i in range(1,10,2):
    arr[i]=arr[i][::-1]

print(arr, type(arr))

[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


In [ ]:
[과제] np.ones((10,10))을 아래와 같이 출력하세요

In [ ]:
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
#임수현
arr = np.ones((10,10))
arr[1:9,1:9] = 0
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
#김나영
#과제: 테두리만 남기고 전부 0으로 변경
arr=np.ones((10,10))
arr[0], arr[9], arr[:,0], arr[:,9] = 0,0,0,0 
arr

In [ ]:
[과제] np.ones((5,5))을 아래와 같이 출력하세요

In [ ]:
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
#임수현
arr = np.zeros((10,10))
arr[2:8,2:8] = 1
arr

In [ ]:
#김나영
#과제: 전부 1인 5x5배열을 -> 9x9배열로 확장, 0 채우기
arr=np.ones((5,5))

v=np.zeros((2,5))
h=np.zeros((9,2))

arr2=np.vstack((arr,v))      # arr 아래에 v 붙이기
arr2=np.vstack((v,arr2))
#print(arr2)

arr2=np.hstack((h,arr2))     # h 옆에 arr2 붙이기
arr2=np.hstack((arr2,h))
print(arr2)

In [ ]:
[과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile 함수)

In [ ]:
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [22]:
#강사님 =정수로 뽑아라
z = np.zeros((8,8),dtype=int)
z[1::2,::2]=1
z[::2,1::2]=1
z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
#김나영
#과제: 전부 0인 배열을 패턴화해서 출력
arr=np.zeros((8,8))

for i in range(8):
    if i%2==0:
        arr[i][1::2]=1     # 짝수 번째 줄 0101010
    else:
        arr[i][0::2]=1     # 홀수 번째 줄 1010101
arr

In [20]:
#임수현
arr = np.zeros((8,8))
for i in range(8):
    for j in range(8):
        if (i + j) % 2 != 0:
            arr[i][j] = 1
print(arr)
#arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))
#print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [ ]:
[과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
np.arange(336).reshape(6,7,8)

In [ ]:
array([[[  0,   1,   2,   3,   4,   5,   6,   7],
        [  8,   9,  10,  11,  12,  13,  14,  15],
        [ 16,  17,  18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29,  30,  31],
        [ 32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53,  54,  55]],

       [[ 56,  57,  58,  59,  60,  61,  62,  63],
        [ 64,  65,  66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87],
        [ 88,  89,  90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101, 102, 103],
        [104, 105, 106, 107, 108, 109, 110, 111]],

       [[112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127],
        [128, 129, 130, 131, 132, 133, 134, 135],
        [136, 137, 138, 139, 140, 141, 142, 143],
        [144, 145, 146, 147, 148, 149, 150, 151],
        [152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 165, 166, 167]],

       [[168, 169, 170, 171, 172, 173, 174, 175],
        [176, 177, 178, 179, 180, 181, 182, 183],
        [184, 185, 186, 187, 188, 189, 190, 191],
        [192, 193, 194, 195, 196, 197, 198, 199],
        [200, 201, 202, 203, 204, 205, 206, 207],
        [208, 209, 210, 211, 212, 213, 214, 215],
        [216, 217, 218, 219, 220, 221, 222, 223]],

       [[224, 225, 226, 227, 228, 229, 230, 231],
        [232, 233, 234, 235, 236, 237, 238, 239],
        [240, 241, 242, 243, 244, 245, 246, 247],
        [248, 249, 250, 251, 252, 253, 254, 255],
        [256, 257, 258, 259, 260, 261, 262, 263],
        [264, 265, 266, 267, 268, 269, 270, 271],
        [272, 273, 274, 275, 276, 277, 278, 279]],

       [[280, 281, 282, 283, 284, 285, 286, 287],
        [288, 289, 290, 291, 292, 293, 294, 295],
        [296, 297, 298, 299, 300, 301, 302, 303],
        [304, 305, 306, 307, 308, 309, 310, 311],
        [312, 313, 314, 315, 316, 317, 318, 319],
        [320, 321, 322, 323, 324, 325, 326, 327],
        [328, 329, 330, 331, 332, 333, 334, 335]]])

In [ ]:
(1, 5, 3)

In [26]:
#임수현
#unravel_index() 함수는 1차원 배열에서 인덱스를 다차원 인덱스 튜플로 반환해주는 함수
arr = np.arange(336).reshape(6,7,8)
np.unravel_index(100, arr.shape)

(1, 5, 4)

In [1]:
#김나영
#[과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스 구하기
arr=np.arange(336).reshape(6,7,8)

b=arr.reshape(-1)
idx=np.where(arr==b[99])     #b의 99인덱스 = arr의 100번째

index=[idx[i][0] for i in range(len(idx))]    #인덱스값 뽑기
print(index)
idx

NameError: name 'np' is not defined