## 피처(feature)? 속성?

피처는 데이터 세트의 일반 속성.
머신러닝은 2차원 이상의 다차원 데이터에서도 많이 사용되므로 타겟값을 제외한 나머지 속성을 모두 피처로 지칭

## 레이블, 클래스, 타겟값. 결정값

타겟값 또는 결정값은 지도 학습 시 데이터의 학습을 위해 주어지는 정답 데이터.
지도 학습 중 분류의 경우에는 이 결정값을 레이블 또는 클래스로 지칭

In [15]:
pip install scikit-learn==1.0.2

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 32.2 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2


분류 (Classification)는 대표적인 지도학습 방법의 하나.
### **지도학습이란**
명확한 답이 주어진 데이터를 먼저 학습 한 뒤, 미지의 정답을 예측하는 방식.
- 학습 데이터 세트/ 테스트 데이터 세트


In [16]:
# 데이터 세트 생성모듈
from sklearn.datasets import load_iris

#의사결정트리 분류모델 DecisionTreeClassifier
#분류 작업에서는 주로 범주형(class) 목표 변수를 예측하는 데 사용
from sklearn.tree import DecisionTreeClassifier as DTC

# 테스트 데이터와 학습 데이터를 분리
from sklearn.model_selection import train_test_split

In [17]:
iris =load_iris()
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [18]:
print(iris.target_names)
iris.feature_names

['setosa' 'versicolor' 'virginica']


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

- sepal length (cm)= 꽃받침 길이(cm)
- sepal width (cm)=  꽃받침 너비(cm)
- petal length (cm)= 꽃잎 길이(cm)
- petal width (cm) = 꽃잎 폭(cm)





In [19]:
# DataFrame으로 반환

import pandas as pd

iris = load_iris() # 붓꽃 데이터셋 로딩

iris_data = iris.data
# iris.data는 iris 데이터세트에 피쳐만으로 된 데이터를 numpy로 가지고 있다.

# iris.target은 붓꽃데이터 세트에서 레이블(결정값) 데이터를 numpy로 가지고 있다.
iris_label = iris.target
print('iris target 값:',iris_label,'\n')
print('iris target 명:', iris.target_names)

#붓꽃 데이터세트를 자세히 보기 위해 DataFrame으로 변환
iris_df = pd.DataFrame( data = iris_data, columns = iris.feature_names)
iris_df['label'] = iris.target
iris_df.head(3)

# 0은 세토사, 1은 베르시칼라, 2는 버지니카를 의미
# 즉, 각 샘플이 어떤 종류의 붓꽃에 속하는지를 나타내는 정보
# 1~ 50번째까지는 세토사, 51~100번째까지는 베르시칼라, 101~150번째까지는 버지니카 = 총 150개

iris target 값: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2] 

iris target 명: ['setosa' 'versicolor' 'virginica']


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   

   label  
0      0  
1      0  
2      0

In [20]:
iris_df. info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   label              150 non-null    int64  
dtypes: float64(4), int64(1)
memory usage: 6.0 KB


In [21]:
# 학습용 데이터와 테스트 데이터 분리
# test_size=0.2 는 테스트 데이터가 20%, 학습데이터가 80%의 비중으로 분할된다는 의미.
# random_state=11 은 호출할 때마다 주어지는 난수 발생값.= seed값과 동일한 역할.

X_train, X_test, y_train,y_test = train_test_split(iris_data, iris_label,
                                                   test_size=0.2, random_state=11)

# X_train( 학습용 '피처' 데이터 세트)  /  y_train( 학습용 '레이블' 데이터 세트)
# X_test( 테스트용 '피처' 데이터 세트) /  y_test( 테스트용 '레이블' 데이터 세트)

In [22]:
len(X_train) # 학습용 피처 데이터세트의 크기 80%

120

In [23]:
len(X_test) # 테스트 피쳐 20%

30

In [24]:
# DecisionTreeClassifier 객체 생성

dt_clf = DTC(random_state=11)

# 학습 수행
dt_clf.fit(X_train, y_train)  # 학습 데이터 기반으로 학습 완료

DecisionTreeClassifier(random_state=11)

In [25]:
# DTC 객체를 이용해 예측 수행
# 예측은 반드시 학습데이터가 아닌 다른 데이터 이용. (테스트 데이터 사용)
# predict() 메소드 : 힉습된 모델 기반에서 테스트 데이터 세트에 대한 예측값 반환

pred = dt_clf.predict(X_test) # = 예측 레이블 데이터 세트

In [26]:
# 의사 결정 트리 기반의 DTC 예측 성능 평가. = 정확도 측정(예측값과 실제 레이블 값이 얼마나 일치하는지 평가하는 지표)
# accuracy_score() 정확도 측정 함수.
# accuracy_score(실제 레이블 데이터 세트, 예측 레이블 데이터 세트)

from sklearn.metrics import accuracy_score
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

예측 정확도: 0.9333


### 위 붓꽃 데이터 세트 분류를 예측한 프로세스
- 데이터 세트 분리: 데이터를 학습 데이터와 테스트 데이터로 분리
- 모델 학습: 학습 데이터를 기반으로 ML 알고리즘을 적용해 모델을 학습
- 예측 수행: 학습된 ML 모델을 이용해 테스트 데이터의 분류(즉, 붓꽃 종류)를 예측합니다
- 평가: 이렇게 예측된 결과값과 테스트 데이터의 실제 결과값을 비교해 ML모델 성능을 평

## Estimator 이해 및 fit(),predict() 메서드
- fit() : ML모델 학습
- predict(): 학습된 모델 예측


Classifier (분류) +  Regressor (회귀) = Estimator(평가자) 클래스

- decomposition (피처 처리 & 차원 축소)
: 차원 축소와 관련한 알고리즘을 지원하는 모듈.  = 차원축소기능 수행
  - from sklearn.decomposition import PCA
  - from sklearn.decomposition import NMF
  - from sklearn.decomposition import Truncated SVD

- cluster (ML 알고리즘)
: 비지도 클러스터링 알고리즘 제공 (K-평균,계층형, DBSCAN등)
  - from sklearn.cluster import KMeans
-
tree (ml 알고리즘)
:의사결정 트리 알고리즘 제공
  - from sklearn.tree import DecisionTreeClassifier # (분류)
  - from sklearn.tree import DecisionTreeRegressor # (회귀)

- metrics (평가)
: 분류, 회귀, 클러스터링, 페어와이즈에 대한 다양한 성능 측정 방법 제공
  - from sklearn.metrics import accuracy_score
  - from sklearn.metrics import mean_squared_error
  - from sklearn.metrics import r2_score
  - from sklearn.metrics import silhouette_samples, silhouette_score
  - from sklearn.metrics import roc_auc_score

- datasets ( 예제 데이터)
: 사이킷 런에 내장된 예제 제공 데이터 세트 생성 모듈
  - from sklearn import datasets
  - from sklearn.datasets import load_iris
    - 분류용
      - datasets.load_iris() # 붓꽃데이터
      - datasets.load_digits() # 0~9까지 숫자의 이미지 픽셀 데이터 세트
      - datasets.load_breast_cancer()  # 위스콘신 유방암 피처들과 악성/음성 데이블 데이터 세트
    - 회귀용
      - datasets.load_boston() : 미국 보스텀의 집 피처들과 가격에 대한 데이터 세트
      - datasets.load_diabetes() : 당뇨 데이터 세트

- pipeline (유틸리티)
: 피처 처리등의 변환과 ML알고리즘 학습, 예측 등을 함께 묶어서 실행할 수 있는 유틸리티 제공
  - from sklearn.pipeline import Pipeline

- preprocessing (피처처리)
 : 데이터 전처리에 필요한 다양한 가공 기능 제공(인코딩/정규화/스케일링 등)
  - from sklearn.preprocessing import LabelEncoder
  - from sklearn.preprocessing import OneHotEncoder, LabelEncoder
  - from sklearn.preprocessing import OneHotEncoder
  - from sklearn.preprocessing import MinMaxScaler
  - from sklearn.preprocessing import PolynomialFeatures
  - from sklearn.preprocessing import StandardScaler as SS
  - from sklearn.preprocessing import scale

- model_selection (데이터 분리,검증& 파라미터 튜닝)
:학습/검증/예측 데이터로 데이터를 분리/평가하기 위한 모듈 모음
  - from sklearn.model_selection import train_test_split # (분리함수)
  - from sklearn.model_selection import StratifiedKFold as SKF
  - from sklearn.model_selection import GridSearchCV # 하이퍼파라미터 튜닝 지원
  - from sklearn.model_selection import KFold
  - from sklearn.model_selection import cross_val_score # 평가함수
  - from sklearn.model_selection import train_test_split

linear_model ( ML알고리즘)
: 주로 선형 회귀, 릿지,라쏘,로지스틱 회귀 등과 SGD 관련 알고리즘 제공.
from sklearn.linear_model import Ridge #회귀
from sklearn.linear_model import Lasso #회귀
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import LinearRegression #회귀

ensemble(ML알고리즘)
: 앙상블 알고리즘 제공.
-랜덤포레스트, 에이더 부스트, 그래디언트 부스팅 등 제공
from sklearn.ensemble import RandomForestRegressor   #회귀
from sklearn.ensemble import RandomForestClassifier #분류
from sklearn.ensemble import GradientBoostingRegressor # 회귀

SVM(ML알고리즘)
: 서포트 벡터 머신 알고리즘 제공

naive_bayes (ML알고리즘)
: 다이브 베이즈 알고리즘 제공. 가우시안NB.다항분포 NB등

neighbors (ML알고리즘)
: 최근접 이웃 알고리즘 제공. K-NN 등

from xgboost import XGBRegressor

from lightgbm import LGBMRegressor


- data = 피쳐의 데이터 세트 [넘파이배열]
- target = 분류시 레이블 값, 회귀일 때는 숫자 결과값 데이터 세트[넘파이배열]
- target_names = 개별 레이블 이름 [넘파이배열 or list타입]
- feature_names = 피처 이름[넘파이배열 or list타입]
- DESCR = 데이터 세트에 대한 설명과 각 피처의 설명  [스트링 타입]

In [27]:
# 붓꽃데이터 생성

from sklearn.datasets import load_iris

iris_data = load_iris()
print(type(iris_data))
# Bunch' 클래스는 파이썬 딕셔너리 자료형과 유사

<class 'sklearn.utils._bunch.Bunch'>


In [28]:
keys = iris_data.keys()
print('붓꽃 데이터 세트의 키들:',keys)

붓꽃 데이터 세트의 키들: dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [29]:
print('\n feature_names 의 타입:', type(iris_data.feature_names))
print('\n feature_names 의 shape:', len(iris_data.feature_names))
print('\n',iris_data.feature_names)

print('\n target_names 의 shape:', len(iris_data.target_names))
print('\n',iris_data.target_names)

print('\n data의 타입: ',type(iris_data.data))
print('\n data의 shape:',iris_data.data.shape,'\n')
print(iris_data['data'])

print('\n target의 타입:',type(iris_data.target))
print('target의 shape:',iris_data.target.shape)
print(iris_data.target)


 feature_names 의 타입: <class 'list'>

 feature_names 의 shape: 4

 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

 target_names 의 shape: 3

 ['setosa' 'versicolor' 'virginica']

 data의 타입:  <class 'numpy.ndarray'>

 data의 shape: (150, 4) 

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [

## train_test_split()
학습/테스트 데이터 세트 분리
- train_test_split(피처 데이터 세트, 레이블 데이터 세트,선택옵션)
  - **test_size** : 전체 데이터에서 테스트 데이터 세트 크기를 얼마로 샘플링 할 것인가 결정. (디폴트 = 0.25 즉, 25%)
  - **train_size** : 학습용 데이터 세트 크기를 얼마로 샘플링 할 것인지 결정.
  - **suffle** : 데이터 분리전 미리 섞을지 결정. 디폴트 True.데이터를 분산시켜 더 효율적인 학습 및 테스트 데이터 만드는데 도움
  - **random_state** : seed와 같은 역할. 랜덤 수 고정.
  - **train_test_split()**: 반환값은 튜플. 순차적으로 학습용 피처세트 > 테스트용 피처세트 > 학습용 레이블 세트 > 테스트용 레이블 세트로 반환됨



In [30]:
# DecisionTreeClassifier 학습
from sklearn.tree import DecisionTreeClassifier as DTC# (분류)
from sklearn.metrics import accuracy_score #평가
from sklearn.datasets import load_iris #데이터 소환
from sklearn.model_selection import train_test_split #분리,검증& 파라미터 튜닝

dt_clf = DTC()
iris_data = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target, \
                                                    test_size = 0.3, random_state = 121)

In [31]:
# 예측 정확도 측정
dt_clf.fit(X_train, y_train)
pred = dt_clf.predict(X_test)
print('예측 정확도: {0:.4f}'.format(accuracy_score(y_test,pred)))

#정확도가 높기는 하나 테스트 데이터가 30%(45개)밖에 되지 않으므로 성능을 판단하기에 적절하지 못함.

예측 정확도: 0.9556


In [32]:
# K-fold 교차 검증

from sklearn.tree import DecisionTreeClassifier as DTC #분류
from sklearn.metrics import accuracy_score # 평가
from sklearn.model_selection import KFold # 분리, 검즘, 파라미터튜닝
import numpy as np

iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DTC(random_state = 156)

# 5개의 폴드 세트로 분리하는 KFold 객체와 폴드 세트별 정확도를 담을 리스트 객체 생성.
kfold = KFold (n_splits = 5) #n_splits = 5 로 객체 생성. 붓꽃데이터를 5개의 폴드 데이터 세트로 분리.(학습 4/5, 검증 1/5)
cv_accuracy = [] # 평균구해서 담아줄 곳
print('붓꽃 데이터 세트 크기:', features.shape[0])


붓꽃 데이터 세트 크기: 150


In [33]:
# split()이 어떤 값을 실제로 반환하는지 확인해보기 위해 검증 데이터 세트의 인덱스도 추출

n_iter = 0 # 반복횟수를 기록하기 위한 변후 초기화

#  kfold.split() 함수를 사용하여 학습 데이터와 검증 데이터의 인덱스를 반환
#  반복문을 통해 각 폴드에 대해 학습과 검증을 수행

for train_index, test_index in kfold.split(features): #5번 반복됨

  # 학습 데이터의 특성(features)과 검증 데이터의 특성을 나누어 가져옵니다.
  X_train, X_test = features[train_index], features[test_index]

  # 학습 데이터의 레이블(label)과 검증 데이터의 레이블을 나누어 가져옵니다.
  y_train, y_test = label[train_index], label[test_index]

  # 학습 및 예측
  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)
  n_iter += 1

  #반복시마다 정확도 측정
  accuracy = np.round(accuracy_score(y_test, pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print('\n # {0} 교차 검증 정확도 : {1}, 학습 데이터 크기 : {2}, 검증 데이터 크기 : {3}'
  .format(n_iter, accuracy, train_size, test_size))

  print('# {0} 검증 세트 인덱스 : {1}'.format(n_iter,test_index))
  cv_accuracy.append(accuracy)

#개별 iteration별 정확도를 합하여 평균 정확도 계산
print('\n ## 평균 검증 정확도: ', np.mean(cv_accuracy))


 # 1 교차 검증 정확도 : 1.0, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
# 1 검증 세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 # 2 교차 검증 정확도 : 0.9667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
# 2 검증 세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

 # 3 교차 검증 정확도 : 0.8667, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
# 3 검증 세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

 # 4 교차 검증 정확도 : 0.9333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
# 4 검증 세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

 # 5 교차 검증 정확도 : 0.7333, 학습 데이터 크기 : 120, 검증 데이터 크기 : 30
# 5 검증 세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

 ## 평균 검증 정확도:  0.9


In [34]:
# Stratified K 폴드
# 불균형한 분포도를 가진 레이블(결정 클래스) 데이터 집합을 위한 K폴드 방식

import pandas as pd

iris = load_iris()

iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [35]:
# 이슈가 발생하도록 3개의 폴드세트를 KFold로 생성

kfold = KFold(n_splits=3)
n_iter = 0

for train_index , test_index in kfold.split(iris_df):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print(' ## 교차 검증: {0}'.format(n_iter),'\n')
  print('▶학습◀ 레이블 데이터 분포 : \n ', label_train.value_counts(),'\n')
  print('▶검증◀ 레이블 데이터 분포: \n', label_test.value_counts(),'\n\n')

# 이런 유형으로 교차 검증 데이터 세트를 분할하면 검증 예측 정확도는 0이 된다.

 ## 교차 검증: 1 

▶학습◀ 레이블 데이터 분포 : 
  1    50
2    50
Name: label, dtype: int64 

▶검증◀ 레이블 데이터 분포: 
 0    50
Name: label, dtype: int64 


 ## 교차 검증: 2 

▶학습◀ 레이블 데이터 분포 : 
  0    50
2    50
Name: label, dtype: int64 

▶검증◀ 레이블 데이터 분포: 
 1    50
Name: label, dtype: int64 


 ## 교차 검증: 3 

▶학습◀ 레이블 데이터 분포 : 
  0    50
1    50
Name: label, dtype: int64 

▶검증◀ 레이블 데이터 분포: 
 2    50
Name: label, dtype: int64 




In [36]:
# StratifiedKFold 교차 검증
# 위와 같이 kfold로 분할된 레이블 데이터 세트가 전체 레이블 값의 분포도를 반영하지 못하는 문제를 해결해준다.
# split()에서드에 인자로 피처 데이터 셋 뿐 아니라 레이블 데이터 세트 값도 반드시 필요함.(kfold는 레이블 없어도 됨)

from sklearn.model_selection import StratifiedKFold as SKF

skf = SKF(n_splits = 3)
n_iter = 0

for train_index, test_index in skf.split(iris_df, iris_df['label']):
  n_iter += 1
  label_train = iris_df['label'].iloc[train_index]
  label_test = iris_df['label'].iloc[test_index]
  print(' ## 교차 검증: {0}'.format(n_iter))
  print('학습 레이블 데이터 분포: \n', label_train.value_counts())
  print('검증 레이블 데이터 분포: \n', label_test.value_counts(),'\n\n')

 ## 교차 검증: 1
학습 레이블 데이터 분포: 
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
1    17
2    16
Name: label, dtype: int64 


 ## 교차 검증: 2
학습 레이블 데이터 분포: 
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 0    17
2    17
1    16
Name: label, dtype: int64 


 ## 교차 검증: 3
학습 레이블 데이터 분포: 
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포: 
 1    17
2    17
0    16
Name: label, dtype: int64 




In [37]:
# StratifiedKFold를 이용해 데이터 분리

dt_clf = DTC(random_state = 156)

skfold = SKF(n_splits = 3)
n_iter = 0
cv_accuracy = []

for train_index, test_index in skfold.split(features,label):
  X_train, X_test = features[train_index], features[test_index]
  y_train, y_test = label[train_index], label[test_index]

  dt_clf.fit(X_train, y_train)
  pred = dt_clf.predict(X_test)

  n_iter += 1
  accuracy = np.round(accuracy_score(y_test, pred),4)
  train_size = X_train.shape[0]
  test_size = X_test.shape[0]
  print(' \n # {0} 교차 검증 정확도: {1}, 학습 데이터 크기: {2}, 검증 데이터 크기 : {3}'
  .format(n_iter, accuracy, train_size, test_size))

  print('# {0} 검증 세트 인덱스: {1}'.format(n_iter, test_index))
  cv_accuracy.append(accuracy)

# 교차 검증별 정확도 및 평균 정확도 계산
print( ' \n ## 교차 검증별 정확도: ', np.round(cv_accuracy, 4))
print( '## 평균 검증 정확도: ', np.round(np.mean(cv_accuracy),4))

# 평균 검증 정확도가 약 96.67% 측정됨
# 왜곡된 레이블 데이터 세트에서는 반드시 Straarified K폴드를 이용해 교차 검증해야 함.+ 분류에서도 마찬가지.
# 회귀에서는 지원되지 않음. (= 회귀 결정값은 연속된 숫자값이기 때문에 결정값별 분포를 정하는 의미가 없음.)

 
 # 1 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기 : 50
# 1 검증 세트 인덱스: [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  50
  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115]
 
 # 2 교차 검증 정확도: 0.94, 학습 데이터 크기: 100, 검증 데이터 크기 : 50
# 2 검증 세트 인덱스: [ 17  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82 116 117 118
 119 120 121 122 123 124 125 126 127 128 129 130 131 132]
 
 # 3 교차 검증 정확도: 0.98, 학습 데이터 크기: 100, 검증 데이터 크기 : 50
# 3 검증 세트 인덱스: [ 34  35  36  37  38  39  40  41  42  43  44  45  46  47  48  49  83  84
  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149]
 
 ## 교차 검증별 정확도:  [0.98 0.94 0.98]
## 평균 검증 정확도:  0.9667


## cross_val_score() 교차 검증

- cross_val_score(estimator, X, y=None, socring = None, n_jobs = 1, verbose = 0, fit_params = None, pre_dispatch = '2*n_jobs')
  - estimator, X, y,socring, cv가 주요 파라미
  - estimator: Classifier(분류) 또는 Regressor(회귀)를 뜻함.
  - X  : 피처 데이터 세트
  - y : 레이블 데이터 세트
  - scoring : 예측 성능 평가 지표
  - cv : 교차 검증 폴수 수


- cross_val_score()는 분류일땐 Stratified K폴드 방식 / 회귀일 때는 K 폴드 방식으로 분할한다.

In [38]:
from sklearn.tree import DecisionTreeClassifier as DTC
from sklearn.model_selection import cross_val_score, cross_validate

iris_data =load_iris()
dt_clf = DTC(random_state = 156)

data = iris_data. data
label = iris_data. target

# accuracy = 정확도
scores = cross_val_score(dt_clf, data, label, scoring = 'accuracy', cv=3)
print('교차 검증별 정확도: ',np.round(scores, 4))
print(' 평균 검증 정확도:', np.round(np.mean(scores),4))

# fit(학습), predict(예측), evaluation(평가)

교차 검증별 정확도:  [0.98 0.94 0.98]
 평균 검증 정확도: 0.9667


# cross_val_score와 cross_validate의 차이
### cross_val_score는 단 하나의 평가 지표만 가능
### cross_validate 여러개의 평가 지표를 반환

-
cross_val_score 함수는 단일 평가 지표에 대한 성능 점수만 반환합니다.
간단한 사용법으로, 모델, 특성 데이터, 타깃 데이터, 평가 지표 등을 인자로 받아 교차 검증을 수행하고, 각 폴드에서의 평가 점수를 리스트 형태로 반환합니다.
주로 간편하게 모델의 성능을 평가하고자 할 때 사용됩니다.

- cross_validate 함수는 cross_val_score보다 더 유연한 기능을 제공합니다.
cross_validate 함수는 다중 평가 지표와 추가적인 정보를 반환합니다.
평가 지표 외에도 훈련 시간, 테스트 시간, 훈련 점수 등의 정보를 반환할 수 있습니다.
return_train_score 매개변수를 사용하여 훈련 점수를 반환할지 여부를 지정할 수 있습니다.
여러 지표를 비교하거나 훈련 시간 등의 추가 정보를 필요로 할 때 사용됩니다.

기본적으로 cross_val_score와 cross_validate 함수는 같은 교차 검증 방법을 사용합니다. 다만 cross_validate는 더 다양한 결과를 제공하며, 추가적인 기능을 활용할 수 있습니다. 따라서 사용 목적에 따라 적절한 함수를 선택하여 사용하면 됩니다.

# GridSearchCV -교차 검증과 최적 하이퍼 파라미터 튜닝을 한번에

하이퍼 파라미터는 머신러닝 알고리즘을 구성하는 주요 구성 요소.
<br>이 값을 조정해 알고리즘의 예측 성능을 개선 할 수 있다.

- 데이터 세트를 cross-vaidation을 위한 학습/테스트 세트로 자동분할한 뒤 하이퍼 파라미터 그리드에 기술된 모든 파라미터를 순차적으로 적용 = 최적 파라미터를 찾을 수 있게 해






GridSearchCV 클래스의 파라미터

- **estimator** : classifier, regressor, pipeline
- **param_grid** : key+리스트 값을 가지는 딕셔너리가 주어짐. estimator의 튜닝을 위해 파라미터 명과 사용될 여러가지 파라미터 값을 지정.
- ** scoring **: 예측 성능을 측정할 평가 방법을 지정.  

In [39]:
# 결정 트리 알고리즘의 여러 하이퍼 파라미터를 순차적으로 변경하면서
# 최고 성능을 가지는 파라미터 조합을 찾고자 한다면
# 다음과 같이 파라미터 집합을 만들고 이를 순차적으로 적용하면서 최적화 수행

grid_parameters = {'max_depth': [1,2,3],
                   'min_samples_split':[2,3]}

In [40]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier as DTC # (분류)
from sklearn.model_selection import GridSearchCV ,train_test_split # 하이퍼파라미터 튜닝. 평가
from sklearn.metrics import accuracy_score # 평가

iris = load_iris()

X_train, X_test, y_train, y_test = train_test_split(iris_data.data, iris_data.target,
                                                    test_size=0.2, random_state=121)
#시간될때 iris_data.data, iris_data.target, 이거 어디서 손봤는지 확인하기

dtree = DTC()

parameters = {'max_depth':[1,2,3],'min_samples_split':[2,3]}

In [41]:
import pandas as pd

# param_grid의 하이퍼 파라미터를 3개의 train, test set fold로 나누어 테스트 수행 설정
# refit=True가 디폴트. 가장 좋은 파라미터 설정으로 재 학습 시킴
# return_train_score=True 는 생략가능. warnning 예방용도인듯?

grid_dtree = GridSearchCV( dtree, param_grid= parameters, cv=3, refit=True, return_train_score=True )
grid_dtree.fit(X_train, y_train)

#  GridSearchCV 결과를 추출해 데이터프레임으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score', 'split0_test_score','split1_test_score','split2_test_score']]

# 6개의 결과 반환
# params컬럼 = 수행할때마다 적용된 하이퍼 파라미터 값
# 4번 행의 rank_test_score가 1이라는건 예측성능이 1위하는 의미 = 5번도 공동 1위
# mean_test_score 총 수행한 평가 평균값.

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [43]:
# GridSearchCV 객체의 fit()을 수행하면 최고 성능을 나타낸 하이퍼 파라미터 값과 그때의 평가 결과값이
# best_params_, best_score_에 기록된다.

print('GridSearchCV 최적 파라미터:', grid_dtree.best_params_)
print('GridSearchCV 최고 정확도 : {0:.4f}'.format(grid_dtree.best_score_))


# 최적 성능을 나타내는 하이퍼 파라미터로 Estimator를 학습해 best_estimator_로 저장

GridSearchCV 최적 파라미터: {'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 : 0.9750


In [44]:
# best_estimator_로 train_test_split()으로 분리된 테스트 데이터 세트에 대해 예측하고 성능을 평가

estimator = grid_dtree.best_estimator_

# GridSearchCV의  best_estimator_ 는 이미 최적 학습이 됐으므로 별도 학습이 필요 없음
pred = estimator.predict(X_test)
print('테스트 데이터 세트 정확도 : {0:.4f}'.format(accuracy_score(y_test, pred)))

테스트 데이터 세트 정확도 : 0.9667


일반적으로 학습데이터를 GridSearchCV를 이용해 최적 하이퍼 파라미터 튜닝을 수행한 뒤 별도의 테스트 세트에서 이를 평가하는 것이 일반적인 머신러닝 적용방법